# Generated by Django 5.1 on 2024-09-08 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_circle_circlemember'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Circle',
            new_name='Pod',
        ),
        migrations.RenameModel(
            old_name='CircleMember',
            new_name='PodMember',
        ),
    ]
