# Generated by Django 5.1 on 2024-09-08 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_connection_connectionstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='podmember',
            old_name='created_at',
            new_name='joined',
        ),
        migrations.RenameField(
            model_name='podmember',
            old_name='circle',
            new_name='pod',
        ),
    ]
