# Generated by Django 5.1 on 2024-10-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_created_at_podmember_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_online',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
